DEFINE TABLE {{db_prefix}}DB_1.INGESTION.RAW_SALES (
	SALE_ID NUMBER(38,0),
	AMOUNT NUMBER(10,2),
	STATUS VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9)
)
    CHANGE_TRACKING = TRUE
    DATA_RETENTION_TIME_IN_DAYS = 1
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 14;