-- Custom Data Sync Task to pull from PROD Share
DEFINE TASK {{db_prefix}}DB_1.INGESTION.SYNC_PROD_DATA
    SCHEDULE = 'USING CRON 0 2 * * * UTC'
    STARTED = TRUE 
AS
    INSERT OVERWRITE INTO {{db_prefix}}DB_1.INGESTION.RAW_SALES
    SELECT * FROM PROD_SHARE_DB.INGESTION.RAW_SALES;